// Generated by: python manage.py export_entity_meta
// Do not edit manually.

/**
 * Runtime array of the catalog entity keys — the subset of
 * {@link ENTITY_META} whose models are `CatalogModel`s. Use this (not
 * `Object.keys(ENTITY_META)` / `k in ENTITY_META`) wherever catalog-only
 * code iterates or membership-tests keys at runtime: a type narrows but
 * cannot exclude a non-catalog key from the actual object.
 *
 * The single enumeration of the catalog vocabulary: {@link CatalogEntityKey}
 * derives from this array and {@link EntityKey} is composed from that.
 */
export const CATALOG_ENTITY_KEYS = [
  'cabinet',
  'corporate-entity',
  'credit-role',
  'display-subtype',
  'display-type',
  'franchise',
  'game-format',
  'gameplay-feature',
  'location',
  'manufacturer',
  'model',
  'person',
  'production-status',
  'reward-type',
  'series',
  'system',
  'tag',
  'technology-generation',
  'technology-subgeneration',
  'theme',
  'title',
] as const;

/** Union of catalog entity `entity_type`s — the `CatalogModel` subset of {@link EntityKey}. */
export type CatalogEntityKey = (typeof CATALOG_ENTITY_KEYS)[number];

/** Union of every entity `entity_type` — the catalog keys plus any non-catalog linkable entities (e.g. a future SSR `user`). */
export type EntityKey = CatalogEntityKey;

/** Identity type that fails to compile unless `S` is a subset of `U`; keeps a generated key subset within {@link EntityKey}. */
type SubsetOf<S extends U, U> = S;

/** Union of entity `entity_type`s that support media uploads. */
export type MediaSupportedEntityKey = SubsetOf<
  'gameplay-feature' | 'manufacturer' | 'model' | 'person',
  EntityKey
>;

/**
 * A forward FK / M2M relationship an entity declares to another entity.
 */
export interface EntityRelationship {
  /** The related entity's `entity_type` */
  entity_target_type: EntityKey;
  /** true for M2M, false for FK */
  many: boolean;
}

/** Per-entity metadata: the shape of each {@link ENTITY_META} value. */
export interface EntityMetadata {
  entity_type: EntityKey;
  entity_type_plural: string;
  label: string;
  label_plural: string;
  relationships: Record<string, EntityRelationship>;
  /** Allowed media-upload categories; `[]` for entities without media. */
  media_categories: readonly string[];
}

/**
 * Registry of entity metadata, keyed by `entity_type`. Source of truth
 * for the frontend's entity-type vocabulary, labels, relationship shapes
 * and media categories. Consumed by polymorphic code (changes feed,
 * JSON-LD assembler, sitemap, taxonomy pages). Generated — do not edit.
 */
export const ENTITY_META = {
  cabinet: {
    entity_type: 'cabinet',
    entity_type_plural: 'cabinets',
    label: 'Cabinet',
    label_plural: 'Cabinets',
    relationships: {},
    media_categories: [],
  },
  'corporate-entity': {
    entity_type: 'corporate-entity',
    entity_type_plural: 'corporate-entities',
    label: 'Corporate Entity',
    label_plural: 'Corporate Entities',
    relationships: {
      manufacturer: { entity_target_type: 'manufacturer', many: false },
    },
    media_categories: [],
  },
  'credit-role': {
    entity_type: 'credit-role',
    entity_type_plural: 'credit-roles',
    label: 'Credit Role',
    label_plural: 'Credit Roles',
    relationships: {
      machine_models: { entity_target_type: 'model', many: true },
      series_credited: { entity_target_type: 'series', many: true },
    },
    media_categories: [],
  },
  'display-subtype': {
    entity_type: 'display-subtype',
    entity_type_plural: 'display-subtypes',
    label: 'Display Subtype',
    label_plural: 'Display Subtypes',
    relationships: {
      display_type: { entity_target_type: 'display-type', many: false },
    },
    media_categories: [],
  },
  'display-type': {
    entity_type: 'display-type',
    entity_type_plural: 'display-types',
    label: 'Display Type',
    label_plural: 'Display Types',
    relationships: {},
    media_categories: [],
  },
  franchise: {
    entity_type: 'franchise',
    entity_type_plural: 'franchises',
    label: 'Franchise',
    label_plural: 'Franchises',
    relationships: {},
    media_categories: [],
  },
  'game-format': {
    entity_type: 'game-format',
    entity_type_plural: 'game-formats',
    label: 'Game Format',
    label_plural: 'Game Formats',
    relationships: {},
    media_categories: [],
  },
  'gameplay-feature': {
    entity_type: 'gameplay-feature',
    entity_type_plural: 'gameplay-features',
    label: 'Gameplay Feature',
    label_plural: 'Gameplay Features',
    relationships: {
      parents: { entity_target_type: 'gameplay-feature', many: true },
    },
    media_categories: ['other'],
  },
  location: {
    entity_type: 'location',
    entity_type_plural: 'locations',
    label: 'Location',
    label_plural: 'Locations',
    relationships: {
      corporate_entities: { entity_target_type: 'corporate-entity', many: true },
      parent: { entity_target_type: 'location', many: false },
    },
    media_categories: [],
  },
  manufacturer: {
    entity_type: 'manufacturer',
    entity_type_plural: 'manufacturers',
    label: 'Manufacturer',
    label_plural: 'Manufacturers',
    relationships: {},
    media_categories: ['logo', 'other'],
  },
  model: {
    entity_type: 'model',
    entity_type_plural: 'models',
    label: 'Model',
    label_plural: 'Models',
    relationships: {
      bootleg_of: { entity_target_type: 'model', many: false },
      cabinet: { entity_target_type: 'cabinet', many: false },
      converted_from: { entity_target_type: 'model', many: false },
      corporate_entity: { entity_target_type: 'corporate-entity', many: false },
      display_subtype: { entity_target_type: 'display-subtype', many: false },
      display_type: { entity_target_type: 'display-type', many: false },
      game_format: { entity_target_type: 'game-format', many: false },
      gameplay_features: { entity_target_type: 'gameplay-feature', many: true },
      licensed_build_of: { entity_target_type: 'model', many: false },
      production_status: { entity_target_type: 'production-status', many: false },
      remake_of: { entity_target_type: 'model', many: false },
      reward_types: { entity_target_type: 'reward-type', many: true },
      system: { entity_target_type: 'system', many: false },
      tags: { entity_target_type: 'tag', many: true },
      technology_generation: { entity_target_type: 'technology-generation', many: false },
      technology_subgeneration: { entity_target_type: 'technology-subgeneration', many: false },
      themes: { entity_target_type: 'theme', many: true },
      title: { entity_target_type: 'title', many: false },
      variant_of: { entity_target_type: 'model', many: false },
    },
    media_categories: ['backglass', 'playfield', 'cabinet', 'other'],
  },
  person: {
    entity_type: 'person',
    entity_type_plural: 'people',
    label: 'Person',
    label_plural: 'People',
    relationships: {},
    media_categories: ['portrait', 'other'],
  },
  'production-status': {
    entity_type: 'production-status',
    entity_type_plural: 'production-statuses',
    label: 'Production Status',
    label_plural: 'Production Statuses',
    relationships: {},
    media_categories: [],
  },
  'reward-type': {
    entity_type: 'reward-type',
    entity_type_plural: 'reward-types',
    label: 'Reward Type',
    label_plural: 'Reward Types',
    relationships: {},
    media_categories: [],
  },
  series: {
    entity_type: 'series',
    entity_type_plural: 'series',
    label: 'Series',
    label_plural: 'Series',
    relationships: {},
    media_categories: [],
  },
  system: {
    entity_type: 'system',
    entity_type_plural: 'systems',
    label: 'System',
    label_plural: 'Systems',
    relationships: {
      manufacturer: { entity_target_type: 'manufacturer', many: false },
      technology_subgeneration: { entity_target_type: 'technology-subgeneration', many: false },
    },
    media_categories: [],
  },
  tag: {
    entity_type: 'tag',
    entity_type_plural: 'tags',
    label: 'Tag',
    label_plural: 'Tags',
    relationships: {},
    media_categories: [],
  },
  'technology-generation': {
    entity_type: 'technology-generation',
    entity_type_plural: 'technology-generations',
    label: 'Technology Generation',
    label_plural: 'Technology Generations',
    relationships: {},
    media_categories: [],
  },
  'technology-subgeneration': {
    entity_type: 'technology-subgeneration',
    entity_type_plural: 'technology-subgenerations',
    label: 'Technology Subgeneration',
    label_plural: 'Technology Subgenerations',
    relationships: {
      technology_generation: { entity_target_type: 'technology-generation', many: false },
    },
    media_categories: [],
  },
  theme: {
    entity_type: 'theme',
    entity_type_plural: 'themes',
    label: 'Theme',
    label_plural: 'Themes',
    relationships: {
      parents: { entity_target_type: 'theme', many: true },
    },
    media_categories: [],
  },
  title: {
    entity_type: 'title',
    entity_type_plural: 'titles',
    label: 'Title',
    label_plural: 'Titles',
    relationships: {
      franchise: { entity_target_type: 'franchise', many: false },
      series: { entity_target_type: 'series', many: false },
    },
    media_categories: [],
  },
} as const satisfies Record<EntityKey, EntityMetadata>;
