// Generated by: python manage.py export_relationship_type_meta
// Do not edit manually.

/** The `ModelRelationship.relationship_type` values — the edge kinds. */
export type RelationshipTypeKey = 'conversion' | 'conversion_kit' | 'copy' | 'retheme';

/** Frontend-relevant per-type facts from RELATIONSHIP_TYPE_BEHAVIOR.
 * `requiresMachineTarget`: the edge must resolve to a seeded machine
 * target (no free-text label rung), so the editor hides the
 * "Describe it" toggle for this type. */
export interface RelationshipTypeMeta {
  key: RelationshipTypeKey;
  requiresMachineTarget: boolean;
}

export const RELATIONSHIP_TYPE_META: Record<RelationshipTypeKey, RelationshipTypeMeta> = {
  conversion: {
    key: 'conversion',
    requiresMachineTarget: false,
  },
  conversion_kit: {
    key: 'conversion_kit',
    requiresMachineTarget: false,
  },
  copy: {
    key: 'copy',
    requiresMachineTarget: false,
  },
  retheme: {
    key: 'retheme',
    requiresMachineTarget: true,
  },
};
