"""Generate frontend/src/lib/models/model-meta.ts from catalog models.

Iterates ``CatalogModel`` subclasses to produce a TypeScript file with:
- CATALOG_META: per-entity record keyed by entity_type, exposing
  entity_type, entity_type_plural, label, label_plural, and a
  ``relationships`` map of forward FK / M2M fields to their
  ``{target_type, many}`` shape. Consumed by polymorphic frontend code
  that needs a typed registry of catalog entities (e.g. the global
  changes feed, prop-type narrowing) and is the source of truth for
  relationship shapes used by the JSON-LD assembler
  (see docs/plans/seo/JsonLdAndFriends.md).
- MEDIA_CATEGORIES: per-entity media category lists, keyed by entity_type.

Run via ``make codegen`` or directly::

    python manage.py export_catalog_meta
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, NamedTuple

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db.models import Model

from apps.catalog._walks import catalog_models
from apps.core.models import LinkableModel


class Relationship(NamedTuple):
    target_type: str
    many: bool


def forward_linkable_relationships(cls: type[Model]) -> dict[str, Relationship]:
    """Forward FK / M2M fields of ``cls`` whose target is a ``LinkableModel``.

    Reverse accessors (``auto_created``) are excluded — only relations the
    entity declares itself, which are the ones its detail response serializes
    as refs. Targets must be ``LinkableModel`` to have a canonical URL the
    frontend can turn into a JSON-LD ``@id``.
    """
    relationships: dict[str, Relationship] = {}
    for f in cls._meta.get_fields():
        target = f.related_model
        if (
            f.is_relation
            and not f.auto_created
            and isinstance(target, type)
            and issubclass(target, LinkableModel)
        ):
            relationships[f.name] = Relationship(
                target.entity_type, bool(f.many_to_many)
            )
    return relationships


class CatalogEntry(NamedTuple):
    entity_type: str
    entity_type_plural: str
    label: str
    label_plural: str
    relationships: dict[str, Relationship]


class Command(BaseCommand):
    help = "Generate frontend/src/lib/models/model-meta.ts from catalog models."

    def handle(
        self,
        **options: Any,  # noqa: ANN401 - argparse-driven Django command kwargs
    ) -> None:
        catalog_meta: list[CatalogEntry] = []
        media_categories: dict[str, list[str]] = {}

        for cls in catalog_models():
            key = cls.entity_type
            label = str(cls._meta.verbose_name).title()
            label_plural = str(cls._meta.verbose_name_plural).title()
            relationships = forward_linkable_relationships(cls)
            catalog_meta.append(
                CatalogEntry(
                    key, cls.entity_type_plural, label, label_plural, relationships
                )
            )
            cats = getattr(cls, "MEDIA_CATEGORIES", [])
            if cats:
                media_categories[key] = list(cats)

        catalog_meta.sort()

        # Every emitted target_type must resolve to a CATALOG_META entry, or the
        # frontend assembler reads relationships[field] as undefined and crashes
        # at render. Today this always holds (every relationship target is itself
        # a CatalogModel); it trips only when a future FK targets a linkable model
        # that isn't a catalog model (e.g. created_by -> user), which is the
        # signal to widen the entry set per JsonLdAndFriends.md.
        keys = {entry.entity_type for entry in catalog_meta}
        for entry in catalog_meta:
            for field, rel in entry.relationships.items():
                if rel.target_type not in keys:
                    raise CommandError(
                        f"{entry.entity_type}.{field} targets "
                        f"'{rel.target_type}', which has no CATALOG_META entry; "
                        f"widen the entry set to cover non-catalog LinkableModels."
                    )

        lines = [
            "// Generated by: python manage.py export_catalog_meta",
            "// Do not edit manually.",
            "",
            "export const CATALOG_META = {",
        ]
        for entry in catalog_meta:
            lines.append(f"\t'{entry.entity_type}': {{")
            lines.append(f"\t\tentity_type: '{entry.entity_type}',")
            lines.append(f"\t\tentity_type_plural: '{entry.entity_type_plural}',")
            lines.append(f"\t\tlabel: '{entry.label}',")
            lines.append(f"\t\tlabel_plural: '{entry.label_plural}',")
            lines.append("\t\trelationships: {")
            for field in sorted(entry.relationships):
                rel = entry.relationships[field]
                many = "true" if rel.many else "false"
                lines.append(
                    f"\t\t\t{field}: {{ target_type: '{rel.target_type}', "
                    f"many: {many} }},"
                )
            lines.append("\t\t},")
            lines.append("\t},")
        lines.append("} as const;")
        lines.append("")
        lines.append("export type CatalogEntityKey = keyof typeof CATALOG_META;")
        lines.append("")
        lines.append("export const MEDIA_CATEGORIES = {")
        for key, cats in sorted(media_categories.items()):
            cats_str = ", ".join(f"'{c}'" for c in cats)
            lines.append(f"\t'{key}': [{cats_str}],")
        lines.append("} as const;")
        lines.append("")

        output_path = (
            Path(settings.BASE_DIR).parent / "frontend/src/lib/models/model-meta.ts"
        )
        output_path.write_text("\n".join(lines))
        self.stdout.write(self.style.SUCCESS(f"Wrote {output_path}"))
