// Generated by: python manage.py export_citation_type_meta
// Do not edit manually.

/** The registered citation-type keys (`CitationSource.source_type` values). */
export type CitationTypeKey = 'book' | 'document' | 'periodical' | 'video' | 'web';

/** Declarative per-type facts, exported from the backend registry.
 * `locatorKind` is the frontend input behavior: `freeform` is a plain
 * text input; `timestamp` adds the type's inline validation.
 * `locatorLabel`/`locatorHelp` are the field label and persistent
 * format guidance the cite picker shows (not placeholder text).
 * `locatorDisplayPrefix` prefixes the locator on the read side
 * (tooltip, references) — e.g. video's `starting at` prefix.
 * `slugAddressed` marks types addressed by an authored kebab slug
 * (periodical issues) — the create UI shows a slug field for these.
 * `childNounPlural` is what the type's children are called in UI
 * copy (a periodical's 'issues') — display vocabulary only.
 * `authoredRootCreation` marks types whose roots may be created
 * through the authored-create form — the create-stage type picker
 * offers exactly these. */
export interface CitationTypeMeta {
  key: CitationTypeKey;
  label: string;
  locatorKind: 'freeform' | 'timestamp';
  locatorLabel: string;
  locatorPlaceholder: string;
  locatorHelp: string;
  locatorDisplayPrefix: string;
  locatorInvalidMessage: string;
  childSkipsLocator: boolean;
  slugAddressed: boolean;
  childNounPlural: string;
  authoredRootCreation: boolean;
}

export const CITATION_TYPE_META: Record<CitationTypeKey, CitationTypeMeta> = {
  book: {
    key: 'book',
    label: 'Book',
    locatorKind: 'freeform',
    locatorLabel: 'Location in source',
    locatorPlaceholder: 'p. 42, Chapter 3, timestamp...',
    locatorHelp: 'e.g. p. 42, Chapter 3, a timestamp',
    locatorDisplayPrefix: '',
    locatorInvalidMessage: '',
    childSkipsLocator: false,
    slugAddressed: false,
    childNounPlural: 'editions',
    authoredRootCreation: true,
  },
  document: {
    key: 'document',
    label: 'Document',
    locatorKind: 'freeform',
    locatorLabel: 'Location in source',
    locatorPlaceholder: 'p. 42, Chapter 3, timestamp...',
    locatorHelp: 'e.g. p. 42, Chapter 3, a timestamp',
    locatorDisplayPrefix: '',
    locatorInvalidMessage: '',
    childSkipsLocator: false,
    slugAddressed: true,
    childNounPlural: 'documents',
    authoredRootCreation: false,
  },
  periodical: {
    key: 'periodical',
    label: 'Periodical',
    locatorKind: 'freeform',
    locatorLabel: 'Location in source',
    locatorPlaceholder: 'p. 42, Chapter 3, timestamp...',
    locatorHelp: 'e.g. p. 42, Chapter 3, a timestamp',
    locatorDisplayPrefix: '',
    locatorInvalidMessage: '',
    childSkipsLocator: false,
    slugAddressed: true,
    childNounPlural: 'issues',
    authoredRootCreation: true,
  },
  video: {
    key: 'video',
    label: 'Video',
    locatorKind: 'timestamp',
    locatorLabel: 'Start time',
    locatorPlaceholder: 'e.g. 1:02:03',
    locatorHelp: 'Where to begin watching \u2014 e.g. 1:02:03, 95, or 1h2m3s',
    locatorDisplayPrefix: 'starting at',
    locatorInvalidMessage:
      'Enter a start time like 1:02:03, 95, or 1h2m3s (where to start watching).',
    childSkipsLocator: false,
    slugAddressed: false,
    childNounPlural: 'videos',
    authoredRootCreation: true,
  },
  web: {
    key: 'web',
    label: 'Web',
    locatorKind: 'freeform',
    locatorLabel: 'Location in source',
    locatorPlaceholder: 'p. 42, Chapter 3, timestamp...',
    locatorHelp: 'e.g. p. 42, Chapter 3, a timestamp',
    locatorDisplayPrefix: '',
    locatorInvalidMessage: '',
    childSkipsLocator: true,
    slugAddressed: false,
    childNounPlural: 'pages',
    authoredRootCreation: false,
  },
};
