// Generated by: python manage.py export_citation_type_meta
// Do not edit manually.

/** The registered citation-type keys (`CitationSource.source_type` values). */
export type CitationTypeKey = 'book' | 'magazine' | 'video' | 'web';

/** Declarative per-type facts, exported from the backend registry.
 * `locatorKind` is the frontend input behavior: `freeform` is a plain
 * text input; `timestamp` adds the type's inline validation. */
export interface CitationTypeMeta {
  key: CitationTypeKey;
  label: string;
  locatorKind: 'freeform' | 'timestamp';
  locatorPlaceholder: string;
  locatorInvalidMessage: string;
  childSkipsLocator: boolean;
}

export const CITATION_TYPE_META: Record<CitationTypeKey, CitationTypeMeta> = {
  book: {
    key: 'book',
    label: 'Book',
    locatorKind: 'freeform',
    locatorPlaceholder: 'p. 42, Chapter 3, timestamp...',
    locatorInvalidMessage: '',
    childSkipsLocator: false,
  },
  magazine: {
    key: 'magazine',
    label: 'Magazine',
    locatorKind: 'freeform',
    locatorPlaceholder: 'p. 42, Chapter 3, timestamp...',
    locatorInvalidMessage: '',
    childSkipsLocator: false,
  },
  video: {
    key: 'video',
    label: 'Video',
    locatorKind: 'timestamp',
    locatorPlaceholder: 'e.g. 1:02:03',
    locatorInvalidMessage:
      'Enter a start time like 1:02:03, 95, or 1h2m3s (where to start watching).',
    childSkipsLocator: false,
  },
  web: {
    key: 'web',
    label: 'Web',
    locatorKind: 'freeform',
    locatorPlaceholder: 'p. 42, Chapter 3, timestamp...',
    locatorInvalidMessage: '',
    childSkipsLocator: true,
  },
};
