# Generated by Django 6.0.7 on 2026-09-07 00:33

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('citation', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_fingerprint', models.CharField(help_text='Hash of the source data file.', max_length=255)),
                ('patch_id', models.CharField(blank=True, db_index=True, help_text='Identity of a data patch (the NNNN-slug filename stem). Null for normal ingests; set for patch applications. The applied-ledger keys on this: a success run with a patch_id means that patch has been applied to this database.', max_length=200, null=True)),
                ('note', models.TextField(blank=True, default='', help_text="Free-text note about the run. For patch runs, holds the patch's description.")),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_default='running', help_text='running — set at creation; a stale running record with an old timestamp indicates a crash. success — transaction committed, all data persisted. failed — exception caught, transaction rolled back.', max_length=10)),
                ('records_parsed', models.PositiveIntegerField(db_default=0)),
                ('records_matched', models.PositiveIntegerField(db_default=0)),
                ('records_created', models.PositiveIntegerField(db_default=0)),
                ('claims_asserted', models.PositiveIntegerField(db_default=0)),
                ('claims_retracted', models.PositiveIntegerField(db_default=0)),
                ('claims_rejected', models.PositiveIntegerField(db_default=0)),
                ('citation_sources_created', models.PositiveIntegerField(db_default=0)),
                ('citation_source_links_created', models.PositiveIntegerField(db_default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('revert', 'Revert')], help_text='What kind of user-driven action this ChangeSet represents. Populated for every user ChangeSet; always NULL for ingest.', max_length=8, null=True)),
                ('note', models.TextField(blank=True, default='', help_text='Optional free-text note explaining the edit.', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('actor', models.ForeignKey(help_text='The actor this changeset is attributed to.', on_delete=django.db.models.deletion.PROTECT, related_name='changesets', to='actors.actor')),
                ('ingest_run', models.ForeignKey(blank=True, help_text='The ingest run that produced this changeset. Null for user edits.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changesets', to='provenance.ingestrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('claim_key', models.CharField(help_text='Identity key for uniqueness. Equals field_name for scalar claims. For relationship claims, encodes the relationship identity by target PK (e.g., "credit|person:42|role:7").', max_length=255)),
                ('value', models.JSONField(help_text='The claimed value. Scalars store the raw value; FK fields store the target row\'s integer PK ("" / null mean cleared); relationship claims store the identity dict plus \'exists\'. PKs — never slugs — so renames can\'t invalidate claims.')),
                ('is_active', models.BooleanField(db_default=True, default=True, help_text='Current assertion from this author for this claim_key on this subject. False = superseded or retracted.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='actors.actor')),
                ('changeset', models.ForeignKey(help_text='The edit session that wrote this claim; carries its attribution.', on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='provenance.changeset')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('license', models.ForeignKey(blank=True, help_text='Per-claim license override. Null inherits from source field license or source default.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.license')),
                ('retracted_by_changeset', models.ForeignKey(blank=True, help_text='The changeset that deactivated this claim (user revert or full_sync retraction).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retracted_claims', to='provenance.changeset')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimCitationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_links', to='citation.citationinstance')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_links', to='provenance.claim')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='citation_instances',
            field=models.ManyToManyField(related_name='claims', through='provenance.ClaimCitationInstance', to='citation.citationinstance'),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('database', 'Database'), ('wiki', 'Wiki'), ('book', 'Book'), ('editorial', 'Editorial'), ('other', 'Other')], default='database', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher priority wins when claims conflict.')),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('is_enabled', models.BooleanField(default=True, help_text='Disabled sources are excluded from claim resolution.')),
                ('actor', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='actors.actor')),
                ('default_license', models.ForeignKey(blank=True, help_text='Default license for claims from this source.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='core.license')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ingestrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingest_runs', to='provenance.source'),
        ),
        migrations.CreateModel(
            name='SourceFieldLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.license')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_licenses', to='provenance.source')),
            ],
        ),
        migrations.AddConstraint(
            model_name='claimcitationinstance',
            constraint=models.UniqueConstraint(fields=('claim', 'citation_instance'), name='prov_claimcite_unique'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['content_type', 'object_id', 'field_name'], name='provenance__content_57ed79_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['content_type', 'object_id', 'claim_key'], name='provenance__content_ae6aad_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['actor', 'content_type', 'object_id'], name='provenance__actor_i_08a433_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['field_name', 'is_active'], name='provenance__field_n_5deecd_idx'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('content_type', 'object_id', 'actor', 'claim_key'), name='provenance_unique_active_claim_per_actor'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('field_name', ''), _negated=True), name='provenance_claim_field_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('claim_key', ''), _negated=True), name='provenance_claim_claim_key_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('claim_key', models.F('field_name')), django.db.models.lookups.Exact(django.db.models.functions.text.Left('claim_key', django.db.models.expressions.CombinedExpression(django.db.models.functions.text.Length('field_name'), '+', models.Value(1))), django.db.models.functions.text.Concat('field_name', models.Value('|'))), _connector='OR'), name='provenance_claim_key_derived_from_field_name', violation_error_code='cross_field', violation_error_message="claim_key must equal field_name, or begin with field_name + '|' for relationship claims."),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('retracted_by_changeset__isnull', True), ('is_active', False), _connector='OR'), name='provenance_claim_retracted_requires_inactive', violation_error_code='cross_field', violation_error_message='retracted_by_changeset is only allowed when is_active=False.'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['-created_at', '-id'], name='provenance_cs_created_id'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['actor', '-created_at'], name='provenance_cs_actor_created'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['actor', 'action', '-created_at'], name='provenance_cs_actor_action'),
        ),
        migrations.AddConstraint(
            model_name='changeset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__isnull', False), ('ingest_run__isnull', True)), models.Q(('action__isnull', True), ('ingest_run__isnull', False)), _connector='OR'), name='provenance_changeset_action_iff_interactive'),
        ),
        migrations.AddConstraint(
            model_name='changeset',
            constraint=models.CheckConstraint(condition=models.Q(('note__length__lte', 1000)), name='provenance_changeset_note_max_length'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='provenance_source_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='provenance_source_slug_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('slug', django.db.models.functions.text.Lower('slug'))), name='provenance_source_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='provenance_source_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['database', 'wiki', 'book', 'editorial', 'other'])), name='provenance_source_source_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 2000)), name='provenance_source_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='ingestrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['running', 'success', 'failed'])), name='provenance_ingestrun_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='ingestrun',
            constraint=models.CheckConstraint(condition=models.Q(('input_fingerprint', ''), _negated=True), name='provenance_ingestrun_fingerprint_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='ingestrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'running')), models.Q(models.Q(('status', 'running'), _negated=True), ('finished_at__isnull', False)), _connector='OR'), name='provenance_ingestrun_finished_iff_not_running', violation_error_code='cross_field', violation_error_message='running requires finished_at=NULL; success/failed requires finished_at to be set.'),
        ),
        migrations.AddConstraint(
            model_name='ingestrun',
            constraint=models.CheckConstraint(condition=models.Q(('patch_id__isnull', True), models.Q(models.Q(('patch_id', ''), _negated=True), ('patch_id', django.db.models.functions.text.Lower('patch_id'))), _connector='OR'), name='provenance_ingestrun_patch_id_lowercase', violation_error_message='patch_id must be a non-empty lowercase string.'),
        ),
        migrations.AddConstraint(
            model_name='ingestrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('patch_id',), name='provenance_ingestrun_patch_applied_once'),
        ),
        migrations.AddConstraint(
            model_name='sourcefieldlicense',
            constraint=models.UniqueConstraint(fields=('source', 'field_name'), name='provenance_sourcefieldlicense_unique_source_field'),
        ),
        migrations.AddConstraint(
            model_name='sourcefieldlicense',
            constraint=models.CheckConstraint(condition=models.Q(('field_name', ''), _negated=True), name='provenance_sourcefieldlicense_field_name_not_blank'),
        ),
    ]
