# Generated by Django 6.0.3 on 2026-06-06 21:46

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0002_alter_changeset_note_alter_citationinstance_locator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestrun',
            name='note',
            field=models.TextField(blank=True, default='', help_text="Free-text note about the run. For patch runs, holds the patch's description."),
        ),
        migrations.AddField(
            model_name='ingestrun',
            name='patch_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identity of a data patch (the NNNN-slug filename stem). Null for normal ingests; set for patch applications. The applied-ledger keys on this: a success run with a patch_id means that patch has been applied to this database.', max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='ingestrun',
            constraint=models.CheckConstraint(condition=models.Q(('patch_id__isnull', True), models.Q(models.Q(('patch_id', ''), _negated=True), ('patch_id', django.db.models.functions.text.Lower('patch_id'))), _connector='OR'), name='provenance_ingestrun_patch_id_lowercase', violation_error_message='patch_id must be a non-empty lowercase string.'),
        ),
        migrations.AddConstraint(
            model_name='ingestrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('patch_id',), name='provenance_ingestrun_patch_applied_once'),
        ),
    ]
