# Generated by Django 6.0.3 on 2026-06-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0004_seed_patch_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestrun',
            name='citation_source_links_created',
            field=models.PositiveIntegerField(db_default=0),
        ),
        migrations.AddField(
            model_name='ingestrun',
            name='citation_sources_created',
            field=models.PositiveIntegerField(db_default=0),
        ),
    ]
