# Generated by Django 6.0.3 on 2026-06-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0002_alter_citationsource_description_and_more'),
        ('provenance', '0007_rewrite_cite_markers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='citationinstance',
            constraint=models.CheckConstraint(condition=models.Q(('slug__length', 8)), name='prov_citinst_slug_length'),
        ),
    ]
