# Generated by Django 6.0.3 on 2026-06-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('provenance', '0014_tighten_actor_schema'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='changeset',
            name='provenance_changeset_user_xor_ingest_run',
        ),
        migrations.RemoveConstraint(
            model_name='changeset',
            name='provenance_changeset_action_iff_user',
        ),
        migrations.RemoveConstraint(
            model_name='claim',
            name='provenance_claim_source_xor_user',
        ),
        migrations.RemoveConstraint(
            model_name='claim',
            name='provenance_unique_active_claim_per_source',
        ),
        migrations.RemoveConstraint(
            model_name='claim',
            name='provenance_unique_active_claim_per_user',
        ),
        migrations.RemoveIndex(
            model_name='changeset',
            name='provenance_cs_user_created',
        ),
        migrations.RemoveIndex(
            model_name='changeset',
            name='provenance_cs_user_action',
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='provenance__source__bf9a7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='provenance__user_id_779f9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='provenance__source__ad9766_idx',
        ),
        migrations.AddConstraint(
            model_name='changeset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__isnull', False), ('ingest_run__isnull', True)), models.Q(('action__isnull', True), ('ingest_run__isnull', False)), _connector='OR'), name='provenance_changeset_action_iff_interactive'),
        ),
        migrations.RemoveField(
            model_name='changeset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='source',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='user',
        ),
    ]
