# Generated by Django 6.0.3 on 2026-06-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provenance", "0015_drop_legacy_attribution"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="claim",
            name="provenance_claim_needs_review_notes_max_length",
        ),
        migrations.RemoveField(
            model_name="claim",
            name="needs_review",
        ),
        migrations.RemoveField(
            model_name="claim",
            name="needs_review_notes",
        ),
    ]
