# Generated by Django 6.0.3 on 2026-07-01 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0016_remove_claim_provenance_claim_needs_review_notes_max_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimCitationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_links', to='provenance.citationinstance')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_links', to='provenance.claim')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('claim', 'citation_instance'), name='prov_claimcite_unique')],
            },
        ),
    ]
