# Generated by Django 6.0.3 on 2026-07-02 08:22
#
# State-only: hand the ``citation_instances`` reverse name from the legacy
# ``CitationInstance.claim`` FK to a ``through`` M2M over the existing
# ``ClaimCitationInstance`` join table. Neither operation changes the schema
# (the join table already exists; a related_name lives only in model state),
# so both are wrapped in SeparateDatabaseAndState — without it, SQLite's
# schema editor would pointlessly rebuild the whole provenance_claim table
# for the M2M AddField.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provenance", "0018_backfill_scalar_citation_joins"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="citationinstance",
                    name="claim",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="provenance.claim",
                    ),
                ),
                migrations.AddField(
                    model_name="claim",
                    name="citation_instances",
                    field=models.ManyToManyField(
                        related_name="claims",
                        through="provenance.ClaimCitationInstance",
                        to="provenance.citationinstance",
                    ),
                ),
            ],
        ),
    ]
