# Generated by Django 6.0.3 on 2026-07-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provenance", "0019_claim_citation_instances_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="citationinstance",
            name="prov_citinst_claim_idx",
        ),
        migrations.RemoveField(
            model_name="citationinstance",
            name="claim",
        ),
    ]
