# Generated by Django 6.0.3 on 2026-07-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0021_relocate_citationinstance_to_citation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='claim',
            name='provenance_claim_citation_max_length',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='citation',
        ),
    ]
