# Generated by Django 6.0.3 on 2026-07-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0024_strip_note_quote_scaffolding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_key',
            field=models.CharField(help_text='Identity key for uniqueness. Equals field_name for scalar claims. For relationship claims, encodes the relationship identity by target PK (e.g., "credit|person:42|role:7").', max_length=255),
        ),
        migrations.AlterField(
            model_name='claim',
            name='value',
            field=models.JSONField(help_text='The claimed value. Scalars store the raw value; FK fields store the target row\'s integer PK ("" / null mean cleared); relationship claims store the identity dict plus \'exists\'. PKs — never slugs — so renames can\'t invalidate claims.'),
        ),
    ]
