# Generated by Django 6.0.7 on 2026-08-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_priority_help_text'),
        ('provenance', '0027_repair_drifted_claim_keys'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['-created_at', '-id'], name='provenance_cs_created_id'),
        ),
    ]
