-- ═══ §170 SHARED HOSTS — hosts that need a tenant path to attribute ════════
-- Generated by: python manage.py export_shared_hosts
-- Do not edit manually — edit apps/citation/shared_hosts.py and re-run
-- `make codegen`.
--
-- A shared host serves many unrelated publishers' files under one hostname,
-- the owning tenant named only by a path segment (a GoDaddy site's documents
-- on img1.wsimg.com/blobby/go/<uuid>, a maker's own facebook.com page). Host-
-- only recognition cannot attribute such a URL, so recognition there is
-- path-scoped and a bare registration is refused.
--
-- Generated because the declaration is Python with no database row behind it:
-- nothing in SQL can read it at query time, and a hand-kept copy has no way to
-- notice it has fallen behind. It did fall behind once, and the loud half was a
-- check firing on a legitimate path-scoped row. The silent half is the one that
-- matters — a host this layer thinks is ordinary keeps its bare row eligible,
-- so citation_root_for_url() attributes every tenant's URL to whoever
-- registered the host, disagreeing with what the app itself resolves.

CREATE OR REPLACE VIEW shared_hosts AS
  SELECT * FROM (VALUES
    ('cdn.shopify.com'       , 'Shopify CDN'),
    ('facebook.com'          , 'Facebook'),
    ('storage.googleapis.com', 'Google Cloud Storage'),
    ('wsimg.com'             , 'GoDaddy Website Builder CDN')
  ) AS t(host, label);
COMMENT ON VIEW shared_hosts IS
  'One row per declared shared multi-tenant host — the host and the platform that serves tenants on it. The widest honest host, matched by label-boundary suffix: a URL is on a shared host when its host equals or ends in one of these. Recognition there is path-scoped, so citation_root_for_host() returns NULL and only citation_root_for_url() can attribute a tenant.';
