# Generated by Django 6.0.7 on 2026-09-07 00:33

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, validators=[apps.core.validators.validate_no_mojibake])),
                ('source_type', models.CharField(choices=[('book', 'Book'), ('periodical', 'Periodical'), ('web', 'Web'), ('video', 'Video'), ('document', 'Document')], max_length=20)),
                ('author', models.CharField(blank=True, max_length=300, validators=[apps.core.validators.validate_no_mojibake])),
                ('publisher', models.CharField(blank=True, max_length=300, validators=[apps.core.validators.validate_no_mojibake])),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('date_note', models.CharField(blank=True, max_length=200, validators=[apps.core.validators.validate_no_mojibake])),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[apps.core.validators.validate_no_mojibake])),
                ('description', models.TextField(blank=True, db_default='', default='', max_length=5000, validators=[apps.core.validators.validate_no_mojibake])),
                ('identifier_key', models.CharField(blank=True, choices=[('dailymotion', 'Dailymotion'), ('facebook', 'Facebook Video'), ('instagram', 'Instagram Reels'), ('ipdb', 'IPDB'), ('opdb', 'OPDB'), ('rumble', 'Rumble'), ('snapchat', 'Snapchat'), ('tiktok', 'TikTok'), ('vimeo', 'Vimeo'), ('x', 'X (Twitter)'), ('youtube', 'YouTube')], db_default='', default='', help_text="Identifies which URL/ID parsing convention applies to this source's children (e.g. 'ipdb' → numeric machine IDs, 'opdb' → slug IDs). Lives on root sources only; children carry `identifier` instead.", max_length=50)),
                ('identifier', models.CharField(blank=True, db_default='', default='', help_text="Structured identifier for this child source within its parent's scheme (e.g. '4443' for IPDB machine 4443). Empty for root sources and children without structured identifiers.", max_length=200)),
                ('slug', models.CharField(blank=True, help_text='Authored kebab handle addressing this source in patch cite refs (<root-slug>:<child-slug>, e.g. billboard:1945-09-29 or williams:wpc-95-schematic-manual). Present exactly on slug-addressed types (periodical, document); null everywhere else.', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('\\A[a-z0-9]+(?:-[a-z0-9]+)*\\Z'), 'Slug may contain only lowercase letters, digits, and hyphens, with no leading, trailing, or repeated hyphens.')])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='actors.actor')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='citation.citationsource')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='actors.actor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CitationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=8, unique=True)),
                ('locator', models.CharField(blank=True, db_default='', default='', max_length=200, validators=[apps.core.validators.validate_no_mojibake])),
                ('quote', models.TextField(blank=True, db_default='', default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('citation_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='citation.citationsource')),
            ],
            options={
                'db_table': 'provenance_citationinstance',
            },
        ),
        migrations.CreateModel(
            name='CitationSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(choices=[('homepage', 'Homepage'), ('catalog', 'Catalog'), ('publisher', 'Publisher'), ('reference', 'Reference'), ('archive', 'Archive')], help_text="Homepage: the source's own front page; Catalog: a third-party catalog or database entry (e.g. IPDB); Publisher: the publisher's page for the work; Reference: the canonical URL of this exact source; Archive: a preserved snapshot such as a Wayback capture", max_length=20)),
                ('url', models.URLField(max_length=2000)),
                ('label', models.CharField(blank=True, max_length=200, validators=[apps.core.validators.validate_no_mojibake])),
                ('citation_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='citation.citationsource')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='actors.actor')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='actors.actor')),
            ],
            options={
                'ordering': ['citation_source', 'link_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CitationSourceRootDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=253)),
                ('path_prefix', models.CharField(blank=True, db_default='', default='', help_text='Scopes recognition to a path slice of a shared multi-tenant CDN host (e.g. /blobby/go/<tenant-uuid> on img1.wsimg.com). Leave blank everywhere else — only declared shared hosts may (and must) carry one.', max_length=300)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='actors.actor')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_domains', to='citation.citationsource')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='actors.actor')),
            ],
            options={
                'ordering': ['host', 'path_prefix'],
            },
        ),
        migrations.CreateModel(
            name='ReservedCitationSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_citation_slugs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='citation_citationsource_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('source_type', ''), _negated=True), name='citation_citationsource_source_type_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['book', 'periodical', 'web', 'video', 'document'])), name='citation_citationsource_source_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('parent', models.F('pk')), _negated=True), _connector='OR'), name='citation_citationsource_parent_not_self', violation_error_code='cross_field', violation_error_message='A citation source cannot be its own parent.'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('year__isnull', True), models.Q(('year__gte', 1800), ('year__lte', 2100)), _connector='OR'), name='citation_citationsource_year_range'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('month__isnull', True), models.Q(('month__gte', 1), ('month__lte', 12)), _connector='OR'), name='citation_citationsource_month_range'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('day__isnull', True), models.Q(('day__gte', 1), ('day__lte', 31)), _connector='OR'), name='citation_citationsource_day_range'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('month__isnull', True), ('year__isnull', False), _connector='OR'), name='citation_citationsource_month_requires_year', violation_error_code='cross_field', violation_error_message='month requires year.'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('day__isnull', True), ('month__isnull', False), _connector='OR'), name='citation_citationsource_day_requires_month', violation_error_code='cross_field', violation_error_message='day requires month.'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('isbn__isnull', True), models.Q(('isbn', ''), _negated=True), _connector='OR'), name='citation_citationsource_isbn_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('identifier_key__in', ['', 'dailymotion', 'facebook', 'instagram', 'ipdb', 'opdb', 'rumble', 'snapchat', 'tiktok', 'vimeo', 'x', 'youtube'])), name='citation_citationsource_identifier_key_valid'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('identifier_key', ''), ('parent__isnull', True), _connector='OR'), name='citation_citationsource_identifier_key_requires_root'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('identifier_key', ''), models.Q(('identifier_key', 'dailymotion'), ('source_type', 'video')), models.Q(('identifier_key', 'facebook'), ('source_type', 'video')), models.Q(('identifier_key', 'instagram'), ('source_type', 'video')), models.Q(('identifier_key', 'ipdb'), ('source_type', 'web')), models.Q(('identifier_key', 'opdb'), ('source_type', 'web')), models.Q(('identifier_key', 'rumble'), ('source_type', 'video')), models.Q(('identifier_key', 'snapchat'), ('source_type', 'video')), models.Q(('identifier_key', 'tiktok'), ('source_type', 'video')), models.Q(('identifier_key', 'vimeo'), ('source_type', 'video')), models.Q(('identifier_key', 'x'), ('source_type', 'web')), models.Q(('identifier_key', 'youtube'), ('source_type', 'video')), _connector='OR'), name='citation_citationsource_identifier_key_scheme_type'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('identifier', ''), ('parent__isnull', False), _connector='OR'), name='citation_citationsource_identifier_requires_parent'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('identifier__gt', ''), ('identifier_key__gt', ''), _negated=True), name='citation_citationsource_identifier_key_or_identifier'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.UniqueConstraint(condition=models.Q(('identifier__gt', '')), fields=('parent', 'identifier'), name='citation_citationsource_unique_child_identifier'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('slug__isnull', True), models.Q(('slug', ''), _negated=True), _connector='OR'), name='citation_citationsource_slug_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('slug', django.db.models.functions.text.Lower('slug'))), name='citation_citationsource_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True), ('slug__isnull', False)), fields=('slug',), name='citation_citationsource_unique_slug_at_root'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False), ('slug__isnull', False)), fields=('parent', 'slug'), name='citation_citationsource_unique_slug_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('slug__isnull', True), ('source_type__in', ['periodical', 'document']), _connector='OR'), name='citation_citationsource_slug_only_when_slug_addressed'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('slug__isnull', False), models.Q(('source_type__in', ['periodical', 'document']), _negated=True), _connector='OR'), name='citation_citationsource_slug_required_when_slug_addressed'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('slug__isnull', True), ('parent__isnull', False), models.Q(('slug__in', ['isbn', 'dailymotion', 'facebook', 'instagram', 'ipdb', 'opdb', 'rumble', 'snapchat', 'tiktok', 'vimeo', 'x', 'youtube']), _negated=True), _connector='OR'), name='citation_citationsource_slug_not_reserved_handle'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 5000)), name='citation_citationsource_description_max_length'),
        ),
        migrations.AddIndex(
            model_name='citationinstance',
            index=models.Index(fields=['citation_source'], name='prov_citinst_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='citationinstance',
            constraint=models.CheckConstraint(condition=models.Q(('slug__length', 8)), name='prov_citinst_slug_length'),
        ),
        migrations.AddConstraint(
            model_name='citationinstance',
            constraint=models.CheckConstraint(condition=models.Q(('quote__length__lte', 2000)), name='citation_citationinstance_quote_max_length'),
        ),
        migrations.AddConstraint(
            model_name='citationsourcelink',
            constraint=models.CheckConstraint(condition=models.Q(('url', ''), _negated=True), name='citation_citationsourcelink_url_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='citationsourcelink',
            constraint=models.CheckConstraint(condition=models.Q(('link_type', ''), _negated=True), name='citation_citationsourcelink_link_type_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='citationsourcelink',
            constraint=models.CheckConstraint(condition=models.Q(('link_type__in', ['homepage', 'catalog', 'publisher', 'reference', 'archive'])), name='citation_citationsourcelink_link_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='citationsourcelink',
            constraint=models.UniqueConstraint(fields=('citation_source', 'url'), name='citation_citationsourcelink_unique_source_url'),
        ),
        migrations.AddConstraint(
            model_name='citationsourcerootdomain',
            constraint=models.CheckConstraint(condition=models.Q(('host', ''), _negated=True), name='citation_citationsourcerootdomain_host_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='citationsourcerootdomain',
            constraint=models.CheckConstraint(condition=models.Q(('host', django.db.models.functions.text.Lower('host'))), name='citation_citationsourcerootdomain_host_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='citationsourcerootdomain',
            constraint=models.UniqueConstraint(fields=('host', 'path_prefix'), name='citation_rootdomain_unique_host_path_prefix', violation_error_message='That domain (or its declared path scope) is already recognized by another citation source.'),
        ),
        migrations.AddConstraint(
            model_name='citationsourcerootdomain',
            constraint=models.CheckConstraint(condition=models.Q(('path_prefix', ''), models.Q(('path_prefix__startswith', '/'), models.Q(('path_prefix__endswith', '/'), _negated=True)), _connector='OR'), name='citation_rootdomain_path_prefix_shape'),
        ),
        migrations.AddConstraint(
            model_name='reservedcitationslug',
            constraint=models.CheckConstraint(condition=models.Q(('slug__length', 8)), name='citation_reserved_slug_length'),
        ),
    ]
