# Generated by Django 6.0.3 on 2026-06-20 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0002_alter_citationsource_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='citationsource',
            name='citation_citationsource_identifier_key_valid',
        ),
        migrations.AlterField(
            model_name='citationsource',
            name='identifier_key',
            field=models.CharField(blank=True, choices=[('ipdb', 'IPDB'), ('opdb', 'OPDB'), ('youtube', 'YouTube')], db_default='', default='', help_text="Identifies which URL/ID parsing convention applies to this source's children (e.g. 'ipdb' → numeric machine IDs, 'opdb' → slug IDs). Lives on root sources only; children carry `identifier` instead.", max_length=50),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('identifier_key__in', ['', 'ipdb', 'opdb', 'youtube'])), name='citation_citationsource_identifier_key_valid'),
        ),
    ]
