# Generated by Django 6.0.3 on 2026-06-20 17:01

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "citation",
            "0003_remove_citationsource_citation_citationsource_identifier_key_valid_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationSourceRootDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("host", models.CharField(max_length=253, unique=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="root_domains",
                        to="citation.citationsource",
                    ),
                ),
            ],
            options={
                "ordering": ["host"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("host", ""), _negated=True),
                        name="citation_citationsourcerootdomain_host_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("host", django.db.models.functions.text.Lower("host"))
                        ),
                        name="citation_citationsourcerootdomain_host_lowercase",
                    ),
                ],
            },
        ),
    ]
