# Generated by Django 6.0.3 on 2026-06-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0005_backfill_citation_root_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationsourcerootdomain',
            name='host',
            field=models.CharField(error_messages={'unique': 'That domain is already recognized by another citation source.'}, max_length=253, unique=True),
        ),
    ]
