# Generated by Django 6.0.3 on 2026-07-02 17:23

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0013_citationinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationinstance',
            name='quote',
            field=models.TextField(blank=True, db_default='', default='', max_length=2000, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AddConstraint(
            model_name='citationinstance',
            constraint=models.CheckConstraint(condition=models.Q(('quote__length__lte', 2000)), name='citation_citationinstance_quote_max_length'),
        ),
    ]
