# Generated by Django 6.0.3 on 2026-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0002_alter_actor_priority_help_text"),
        ("citation", "0014_citationinstance_quote_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="citationsource",
            name="citation_citationsource_source_type_valid",
        ),
        migrations.RemoveConstraint(
            model_name="citationsource",
            name="citation_citationsource_identifier_key_requires_web",
        ),
        migrations.AlterField(
            model_name="citationsource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("book", "Book"),
                    ("magazine", "Magazine"),
                    ("web", "Web"),
                    ("video", "Video"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_type__in", ["book", "magazine", "web", "video"])
                ),
                name="citation_citationsource_source_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identifier_key", ""),
                    ("source_type__in", ["web", "video"]),
                    _connector="OR",
                ),
                name="citation_citationsource_identifier_key_scheme_type",
            ),
        ),
    ]
