# Generated by Django 6.0.3 on 2026-07-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_priority_help_text'),
        ('citation', '0015_video_source_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='citationsource',
            name='citation_citationsource_identifier_key_scheme_type',
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('identifier_key', ''), models.Q(('identifier_key', 'ipdb'), ('source_type', 'web')), models.Q(('identifier_key', 'opdb'), ('source_type', 'web')), models.Q(('identifier_key', 'youtube'), ('source_type', 'video')), _connector='OR'), name='citation_citationsource_identifier_key_scheme_type'),
        ),
    ]
