# Generated by Django 6.0.3 on 2026-07-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_priority_help_text'),
        ('citation', '0017_more_video_schemes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='citationsource',
            name='citation_citationsource_identifier_key_valid',
        ),
        migrations.RemoveConstraint(
            model_name='citationsource',
            name='citation_citationsource_identifier_key_scheme_type',
        ),
        migrations.AlterField(
            model_name='citationsource',
            name='identifier_key',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram Reels'), ('ipdb', 'IPDB'), ('opdb', 'OPDB'), ('rumble', 'Rumble'), ('snapchat', 'Snapchat'), ('tiktok', 'TikTok'), ('vimeo', 'Vimeo'), ('x', 'X (Twitter)'), ('youtube', 'YouTube')], db_default='', default='', help_text="Identifies which URL/ID parsing convention applies to this source's children (e.g. 'ipdb' → numeric machine IDs, 'opdb' → slug IDs). Lives on root sources only; children carry `identifier` instead.", max_length=50),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('identifier_key__in', ['', 'instagram', 'ipdb', 'opdb', 'rumble', 'snapchat', 'tiktok', 'vimeo', 'x', 'youtube'])), name='citation_citationsource_identifier_key_valid'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('identifier_key', ''), models.Q(('identifier_key', 'instagram'), ('source_type', 'video')), models.Q(('identifier_key', 'ipdb'), ('source_type', 'web')), models.Q(('identifier_key', 'opdb'), ('source_type', 'web')), models.Q(('identifier_key', 'rumble'), ('source_type', 'video')), models.Q(('identifier_key', 'snapchat'), ('source_type', 'video')), models.Q(('identifier_key', 'tiktok'), ('source_type', 'video')), models.Q(('identifier_key', 'vimeo'), ('source_type', 'video')), models.Q(('identifier_key', 'x'), ('source_type', 'web')), models.Q(('identifier_key', 'youtube'), ('source_type', 'video')), _connector='OR'), name='citation_citationsource_identifier_key_scheme_type'),
        ),
    ]
