# Generated by Django 6.0.3 on 2026-07-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0019_facebook_dailymotion_video_schemes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationsourcelink',
            name='link_type',
            field=models.CharField(choices=[('homepage', 'Homepage'), ('catalog', 'Catalog'), ('publisher', 'Publisher'), ('reference', 'Reference'), ('archive', 'Archive')], help_text="Homepage: the source's own front page; Catalog: a third-party catalog or database entry (e.g. IPDB); Publisher: the publisher's page for the work; Reference: the canonical URL of this exact source; Archive: a preserved snapshot such as a Wayback capture", max_length=20),
        ),
    ]
