# Generated by Django 6.0.3 on 2026-07-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0021_reservedcitationslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationinstance',
            name='quote',
            field=models.TextField(blank=True, db_default='', default='', max_length=2000),
        ),
    ]
