# Generated by Django 6.0.6 on 2026-07-23 05:25, then split by hand:
# this migration adds the nullable column and backfills it; 0025 adds the
# constraints (including required-slug). Two files so the backfill is
# testable at this frozen state — once 0025 lands, a slugless periodical row
# can no longer be created to exercise it.

import django.core.validators
import re
from django.db import migrations, models
from django.utils.text import slugify

# Frozen at authoring time (slug-addressed = periodical), matching the frozen
# constraint conditions in 0025 — a migration must not read the live registry.
_SLUG_ADDRESSED_TYPES = ["periodical"]

# The slug column's max_length, frozen like the type list. The base is cut
# shorter to leave headroom for the ``-N`` dedup suffix, since ``name`` (500
# chars) can slugify past the column — SQLite would store the overflow
# silently while Postgres would fail the migration mid-backfill.
_SLUG_MAX_LENGTH = 200
_SLUG_BASE_MAX_LENGTH = 190


def backfill_slugs(apps, schema_editor):
    """Slugify every slug-addressed row's name, deduped within its parent.

    The one place ``slugify`` runs at all — every other path (patch node, API
    create) requires an authored slug. Verified against the local catalog (18
    periodical roots + 1 child): no collisions, no empty results. Prod may
    differ, so a name that slugifies to nothing raises — an unaddressable row
    needs a human-authored handle, not minted junk — and the final assertion
    trusts a recount, not the loop. An over-long name is truncated to the
    column bound instead (a shortened handle is still a valid, addressable
    one), with the cut stripped of any trailing hyphen so the grammar CHECKs
    in 0025 hold.
    """
    CitationSource = apps.get_model("citation", "CitationSource")
    used: dict[int | None, set[str]] = {}
    rows = CitationSource.objects.filter(
        source_type__in=_SLUG_ADDRESSED_TYPES, slug__isnull=True
    ).order_by("pk")
    for row in rows:
        base = slugify(row.name)[:_SLUG_BASE_MAX_LENGTH].rstrip("-")
        if not base:
            raise RuntimeError(
                f"CitationSource {row.pk} ({row.name!r}) slugifies to nothing; "
                f"author a slug for it before migrating."
            )
        taken = used.setdefault(row.parent_id, set())
        slug, n = base, 2
        while slug in taken:
            slug, n = f"{base}-{n}", n + 1
        assert len(slug) <= _SLUG_MAX_LENGTH
        taken.add(slug)
        row.slug = slug
        row.save(update_fields=["slug"])
    remaining = CitationSource.objects.filter(
        source_type__in=_SLUG_ADDRESSED_TYPES, slug__isnull=True
    ).count()
    if remaining:
        raise RuntimeError(f"{remaining} slug-addressed rows still unslugged.")


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_priority_help_text'),
        ('citation', '0023_periodical_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationsource',
            name='slug',
            field=models.CharField(blank=True, help_text='Authored kebab handle addressing this source in patch cite refs (<periodical-slug>:<issue-slug>, e.g. billboard:1945-09-29). Present exactly on slug-addressed types (periodical); null everywhere else.', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-z0-9]+(?:-[a-z0-9]+)*$'), 'Slug may contain only lowercase letters, digits, and hyphens, with no leading, trailing, or repeated hyphens.')]),
        ),
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
    ]
