# Generated by Django 6.0.6 on 2026-07-23 18:16

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0024_citationsource_slug_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationsource',
            name='slug',
            field=models.CharField(blank=True, help_text='Authored kebab handle addressing this source in patch cite refs (<magazine-slug>:<issue-slug>, e.g. billboard:1945-09-29). Present exactly on slug-addressed types (magazine); null everywhere else.', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('\\A[a-z0-9]+(?:-[a-z0-9]+)*\\Z'), 'Slug may contain only lowercase letters, digits, and hyphens, with no leading, trailing, or repeated hyphens.')]),
        ),
    ]
