# Generated by Django 6.0.6 on 2026-07-23 05:25, then split by hand (see
# 0024): the constraints land only after 0024's backfill has slugged every
# existing periodical row. Conditions are frozen serializations of the type
# registry (slug-addressed = periodical) and the reserved cite handles
# (isbn + the scheme keys) as of authoring time; a registry change flows
# into a fresh makemigrations, never an edit here.

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0024_citationsource_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('slug__isnull', True), models.Q(('slug', ''), _negated=True), _connector='OR'), name='citation_citationsource_slug_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('slug', django.db.models.functions.text.Lower('slug'))), name='citation_citationsource_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True), ('slug__isnull', False)), fields=('slug',), name='citation_citationsource_unique_slug_at_root'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False), ('slug__isnull', False)), fields=('parent', 'slug'), name='citation_citationsource_unique_slug_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('slug__isnull', True), ('source_type__in', ['periodical']), _connector='OR'), name='citation_citationsource_slug_only_when_slug_addressed'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('slug__isnull', False), models.Q(('source_type__in', ['periodical']), _negated=True), _connector='OR'), name='citation_citationsource_slug_required_when_slug_addressed'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('slug__isnull', True), ('parent__isnull', False), models.Q(('slug__in', ['isbn', 'dailymotion', 'facebook', 'instagram', 'ipdb', 'opdb', 'rumble', 'snapchat', 'tiktok', 'vimeo', 'x', 'youtube']), _negated=True), _connector='OR'), name='citation_citationsource_slug_not_reserved_handle'),
        ),
    ]
