# Generated by Django 6.0.6 on 2026-08-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_priority_help_text'),
        ('citation', '0026_alter_citationsource_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citationsourcerootdomain',
            options={'ordering': ['host', 'path_prefix']},
        ),
        migrations.AddField(
            model_name='citationsourcerootdomain',
            name='path_prefix',
            field=models.CharField(blank=True, db_default='', default='', help_text='Scopes recognition to a path slice of a shared multi-tenant CDN host (e.g. /blobby/go/<tenant-uuid> on img1.wsimg.com). Leave blank everywhere else — only declared shared hosts may (and must) carry one.', max_length=300),
        ),
        migrations.AlterField(
            model_name='citationsourcerootdomain',
            name='host',
            field=models.CharField(max_length=253),
        ),
        migrations.AddConstraint(
            model_name='citationsourcerootdomain',
            constraint=models.UniqueConstraint(fields=('host', 'path_prefix'), name='citation_rootdomain_unique_host_path_prefix', violation_error_message='That domain (or its declared path scope) is already recognized by another citation source.'),
        ),
        migrations.AddConstraint(
            model_name='citationsourcerootdomain',
            constraint=models.CheckConstraint(condition=models.Q(('path_prefix', ''), models.Q(('path_prefix__startswith', '/'), models.Q(('path_prefix__endswith', '/'), _negated=True)), _connector='OR'), name='citation_rootdomain_path_prefix_shape'),
        ),
    ]
