# Generated by Django 6.0.6 on 2026-08-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_priority_help_text'),
        ('citation', '0027_alter_citationsourcerootdomain_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='citationsource',
            name='citation_citationsource_source_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='citationsource',
            name='citation_citationsource_slug_only_when_slug_addressed',
        ),
        migrations.RemoveConstraint(
            model_name='citationsource',
            name='citation_citationsource_slug_required_when_slug_addressed',
        ),
        migrations.AlterField(
            model_name='citationsource',
            name='source_type',
            field=models.CharField(choices=[('book', 'Book'), ('periodical', 'Periodical'), ('web', 'Web'), ('video', 'Video'), ('document', 'Document')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['book', 'periodical', 'web', 'video', 'document'])), name='citation_citationsource_source_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('slug__isnull', True), ('source_type__in', ['periodical', 'document']), _connector='OR'), name='citation_citationsource_slug_only_when_slug_addressed'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('slug__isnull', False), models.Q(('source_type__in', ['periodical', 'document']), _negated=True), _connector='OR'), name='citation_citationsource_slug_required_when_slug_addressed'),
        ),
    ]
