# Generated by Django 6.0.6 on 2026-08-12 15:53

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0028_document_citation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationsource',
            name='slug',
            field=models.CharField(blank=True, help_text='Authored kebab handle addressing this source in patch cite refs (<root-slug>:<child-slug>, e.g. billboard:1945-09-29 or williams:wpc-95-schematic-manual). Present exactly on slug-addressed types (periodical, document); null everywhere else.', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('\\A[a-z0-9]+(?:-[a-z0-9]+)*\\Z'), 'Slug may contain only lowercase letters, digits, and hyphens, with no leading, trailing, or repeated hyphens.')]),
        ),
    ]
