# Generated by Django 6.0.3 on 2026-05-29 22:07

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_location_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='machinemodel',
            name='catalog_machinemodel_pinside_id_min',
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='pinside_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, validators=[apps.core.validators.validate_no_mojibake], verbose_name='Pinside ID'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('pinside_id__isnull', True), models.Q(('pinside_id', ''), _negated=True), _connector='OR'), name='catalog_machinemodel_pinside_id_not_empty'),
        ),
    ]
