# Generated by Django 6.0.3 on 2026-06-06 01:08

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_unaccent_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemodel',
            name='ipdb_id',
            field=models.PositiveIntegerField(blank=True, help_text='Internet Pinball Database numeric id for this machine.', null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='IPDB ID'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='opdb_id',
            field=models.CharField(blank=True, help_text="Open Pinball Database id (e.g. 'GRBE5-MQK7e').", max_length=50, null=True, unique=True, validators=[apps.core.validators.validate_no_mojibake], verbose_name='OPDB ID'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='pinside_id',
            field=models.CharField(blank=True, help_text='Pinside.com game id slug for this machine.', max_length=120, null=True, unique=True, validators=[apps.core.validators.validate_no_mojibake], verbose_name='Pinside ID'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='production_quantity',
            field=models.CharField(blank=True, help_text="Number of units produced, as free text (e.g. '6,000' or 'unknown').", max_length=100, validators=[apps.core.validators.validate_no_mojibake]),
        ),
    ]
