# Generated by Django 6.0.3 on 2026-06-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_machinemodel_ipdb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemodel',
            name='cabinet',
            field=models.ForeignKey(blank=True, help_text='Cabinet form factor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='catalog.cabinet'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='converted_from',
            field=models.ForeignKey(blank=True, help_text='Source machine if this is a conversion/retheme.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='catalog.machinemodel'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='corporate_entity',
            field=models.ForeignKey(blank=True, help_text='Specific corporate incarnation that produced this model.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='catalog.corporateentity'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='display_subtype',
            field=models.ForeignKey(blank=True, help_text='Display subtype.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='catalog.displaysubtype'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='display_type',
            field=models.ForeignKey(blank=True, help_text='Display type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='catalog.displaytype'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='game_format',
            field=models.ForeignKey(blank=True, help_text='Game format.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='catalog.gameformat'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='remake_of',
            field=models.ForeignKey(blank=True, help_text='Original model if this is a remake.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remakes', to='catalog.machinemodel'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='technology_generation',
            field=models.ForeignKey(blank=True, help_text='Technology generation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='catalog.technologygeneration'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='technology_subgeneration',
            field=models.ForeignKey(blank=True, help_text='Technology subgeneration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='catalog.technologysubgeneration'),
        ),
    ]
