# Generated by Django 6.0.3 on 2026-06-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_machinemodel_cabinet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemodel',
            name='system',
            field=models.ForeignKey(blank=True, help_text='Hardware system.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='catalog.system'),
        ),
    ]
