# Generated by Django 6.0.3 on 2026-06-06 10:56

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_machinemodel_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='short_name',
            field=models.CharField(blank=True, help_text="Compact display form of the name, e.g. 'USA' for 'United States of America'.", max_length=100, validators=[apps.core.validators.validate_no_mojibake]),
        ),
    ]
