# Generated by Django 6.0.3 on 2026-06-08 14:44

import apps.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_location_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('deleted', 'Deleted')], max_length=10, null=True)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('name', models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake])),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'production statuses',
                'ordering': ['display_order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='catalog_productionstatus_slug_not_blank'), models.CheckConstraint(condition=models.Q(('slug', django.db.models.functions.text.Lower('slug'))), name='catalog_productionstatus_slug_lowercase'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'deleted']), ('status__isnull', True), _connector='OR'), name='catalog_productionstatus_status_valid'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='catalog_productionstatus_name_not_blank'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_productionstatus_unique_name_ci'), models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_productionstatus_description_max_length')],
            },
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='production_status',
            field=models.ForeignKey(blank=True, help_text='Commercial production status.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='catalog.productionstatus'),
        ),
    ]
