# Generated by Django 6.0.3 on 2026-06-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_productionstatus_machinemodel_production_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemodel',
            name='cabinet',
            field=models.ForeignKey(blank=True, help_text='Form factor of the physical cabinet.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='catalog.cabinet'),
        ),
    ]
