# Generated by Django 6.0.3 on 2026-06-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_machinemodel_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateentity',
            name='operating_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('ended', 'Ended'), ('unknown', 'Unknown')], default='unknown', help_text='Whether this corporate entity is still producing pinball.', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='corporateentity',
            constraint=models.CheckConstraint(condition=models.Q(('operating_status__in', ['ongoing', 'ended', 'unknown'])), name='catalog_corporateentity_operating_status_valid'),
        ),
    ]
