# Generated by Django 6.0.3 on 2026-06-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_corporateentity_operating_status_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="title",
            name="catalog_title_needs_review_notes_max_length",
        ),
        migrations.RemoveField(
            model_name="title",
            name="needs_review",
        ),
        migrations.RemoveField(
            model_name="title",
            name="needs_review_notes",
        ),
    ]
