# Generated by Django 6.0.3 on 2026-06-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_title_catalog_title_needs_review_notes_max_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateentitylocation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='corporateentitylocation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='machinemodelgameplayfeature',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='machinemodelgameplayfeature',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='machinemodelrewardtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='machinemodelrewardtype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='machinemodeltag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='machinemodeltag',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='machinemodeltheme',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='machinemodeltheme',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='modelabbreviation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='modelabbreviation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='titleabbreviation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='titleabbreviation',
            name='updated_at',
        ),
    ]
