# Generated by Django 6.0.3 on 2026-06-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_corporateentitylocation_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateentityalias',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='corporateentityalias',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='gameplayfeaturealias',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gameplayfeaturealias',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='locationalias',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='locationalias',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='manufactureralias',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='manufactureralias',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='personalias',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='personalias',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rewardtypealias',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rewardtypealias',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='themealias',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='themealias',
            name='updated_at',
        ),
    ]
