# Generated by Django 6.0.3 on 2026-06-29 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Promote the self-referential ``parents`` M2Ms to explicit through-models.

    ``Theme.parents`` / ``GameplayFeature.parents`` already materialize into
    Django's implicit M2M tables ``catalog_theme_parents`` /
    ``catalog_gameplayfeature_parents``. The new ``ThemeParent`` /
    ``GameplayFeatureParent`` through-models are pinned to those exact tables,
    columns (``from_*_id`` / ``to_*_id``), CASCADE FKs and unnamed unique index,
    so promoting them is a **state-only** change: Django's project state learns
    the explicit models while the database is untouched. Hence
    ``SeparateDatabaseAndState`` with empty ``database_operations`` — no DDL,
    no data movement. The four state operations are the autodetector's verbatim
    output (each ``CreateModel`` precedes the ``AlterField`` that references it
    via ``through=``).
    """

    dependencies = [
        ('catalog', '0015_remove_corporateentityalias_created_at_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='GameplayFeatureParent',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('from_gameplayfeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.gameplayfeature')),
                        ('to_gameplayfeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.gameplayfeature')),
                    ],
                    options={
                        'db_table': 'catalog_gameplayfeature_parents',
                        'unique_together': {('from_gameplayfeature', 'to_gameplayfeature')},
                    },
                ),
                migrations.AlterField(
                    model_name='gameplayfeature',
                    name='parents',
                    field=models.ManyToManyField(blank=True, help_text='Parent features in the hierarchy (materialized from relationship claims).', related_name='children', through='catalog.GameplayFeatureParent', through_fields=('from_gameplayfeature', 'to_gameplayfeature'), to='catalog.gameplayfeature'),
                ),
                migrations.CreateModel(
                    name='ThemeParent',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('from_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.theme')),
                        ('to_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.theme')),
                    ],
                    options={
                        'db_table': 'catalog_theme_parents',
                        'unique_together': {('from_theme', 'to_theme')},
                    },
                ),
                migrations.AlterField(
                    model_name='theme',
                    name='parents',
                    field=models.ManyToManyField(blank=True, help_text='Parent themes in the hierarchy (materialized from relationship claims).', related_name='children', through='catalog.ThemeParent', through_fields=('from_theme', 'to_theme'), to='catalog.theme'),
                ),
            ],
            database_operations=[],
        ),
    ]
