# Generated by Django 6.0.3 on 2026-07-07 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_promote_parent_through_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinemodel",
            name="bootleg_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Original machine this is an unauthorized copy (bootleg) of. Unlike remakes and conversions, may belong to a different Title.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bootlegs",
                to="catalog.machinemodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="machinemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("bootleg_of__isnull", True),
                    models.Q(("bootleg_of", models.F("pk")), _negated=True),
                    _connector="OR",
                ),
                name="catalog_machinemodel_bootleg_of_not_self",
                violation_error_code="cross_field",
                violation_error_message="A machine model cannot be a bootleg of itself.",
            ),
        ),
    ]
