# Generated by Django 6.0.3 on 2026-07-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_machinemodel_bootleg_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemodel',
            name='licensed_build_of',
            field=models.ForeignKey(blank=True, help_text='Original machine this is an officially licensed build (by a licensee or subsidiary) of. Like bootlegs, may belong to a different Title.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licensed_builds', to='catalog.machinemodel'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('licensed_build_of__isnull', True), models.Q(('licensed_build_of', models.F('pk')), _negated=True), _connector='OR'), name='catalog_machinemodel_licensed_build_of_not_self', violation_error_code='cross_field', violation_error_message='A machine model cannot be a licensed build of itself.'),
        ),
    ]
