# Generated by Django 6.0.6 on 2026-07-14 01:25

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_license_sidecar_slug_to_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_label', models.CharField(blank=True, default='', help_text='Free-text target descriptor when the donor isn\'t seeded ("an unknown 1960s replay game"). Empty when target_machine is set.', max_length=300, validators=[apps.core.validators.validate_no_mojibake])),
                ('relationship_type', models.CharField(choices=[('conversion', 'Conversion'), ('conversion_kit', 'Conversion kit'), ('copy', 'Copy')], help_text='How the subject relates to the target.', max_length=20)),
                ('license_status', models.CharField(choices=[('licensed', 'Licensed'), ('unlicensed', 'Unlicensed'), ('unknown', 'Unknown')], default='unknown', help_text='Whether the relationship was authorized by the rights holder.', max_length=20)),
                ('machine_model', models.ForeignKey(help_text='The subject model this edge belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='catalog.machinemodel')),
                ('target_machine', models.ForeignKey(blank=True, help_text='The fully-resolved target/donor, when known and seeded.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_relationships', to='catalog.machinemodel')),
            ],
            options={
                'verbose_name': 'model relationship',
                'verbose_name_plural': 'model relationships',
                'indexes': [models.Index(fields=['relationship_type', 'license_status'], name='catalog_mod_relatio_d29009_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('target_label', ''), ('target_machine__isnull', False)), models.Q(('target_machine__isnull', True), models.Q(('target_label', ''), _negated=True)), _connector='OR'), name='catalog_modelrelationship_target_xor', violation_error_code='cross_field', violation_error_message='Set either target_machine or target_label — never both, never neither.'), models.CheckConstraint(condition=models.Q(('target_machine__isnull', True), models.Q(('target_machine', models.F('machine_model')), _negated=True), _connector='OR'), name='catalog_modelrelationship_target_not_self', violation_error_code='cross_field', violation_error_message='A machine model cannot have a relationship to itself.'), models.CheckConstraint(condition=models.Q(('relationship_type__in', ['conversion', 'conversion_kit', 'copy'])), name='catalog_modelrelationship_type_valid'), models.CheckConstraint(condition=models.Q(('license_status__in', ['licensed', 'unlicensed', 'unknown'])), name='catalog_modelrelationship_license_status_valid'), models.UniqueConstraint(condition=models.Q(('target_machine__isnull', False)), fields=('machine_model', 'target_machine'), name='catalog_modelrelationship_unique_machine_target'), models.UniqueConstraint(condition=models.Q(('target_machine__isnull', True)), fields=('machine_model',), name='catalog_modelrelationship_unique_label_target')],
            },
        ),
    ]
