# Generated by Django 6.0.6 on 2026-07-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_drop_legacy_lineage_columns'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modelrelationship',
            name='catalog_modelrelationship_type_valid',
        ),
        migrations.AlterField(
            model_name='modelrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('conversion', 'Conversion'), ('conversion_kit', 'Conversion kit'), ('copy', 'Copy'), ('retheme', 'Re-theme')], help_text='How the subject relates to the target.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='modelrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('relationship_type__in', ['conversion', 'conversion_kit', 'copy', 'retheme'])), name='catalog_modelrelationship_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='modelrelationship',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('relationship_type__in', ('retheme',)), _negated=True), ('target_machine__isnull', False), _connector='OR'), name='catalog_modelrelationship_machine_target_required', violation_error_code='cross_field', violation_error_message='This relationship type requires a seeded target machine, not a text label.'),
        ),
    ]
