# Generated by Django 6.0.6 on 2026-07-19 10:09

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_retheme_relationship_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelExportMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_market_label', models.CharField(blank=True, default='', help_text='Free-text market descriptor when the market is not a country ("Europe"). Empty when target_market_location is set, and empty on the unknown-market row.', max_length=120, validators=[apps.core.validators.validate_no_mojibake])),
            ],
            options={
                'verbose_name': 'model export market',
                'verbose_name_plural': 'model export markets',
            },
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='export_edition_of',
            field=models.ForeignKey(blank=True, help_text='Domestic original if this model was built for an export market.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_editions', to='catalog.machinemodel'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('export_edition_of__isnull', True), models.Q(('export_edition_of', models.F('pk')), _negated=True), _connector='OR'), name='catalog_machinemodel_export_edition_of_not_self', violation_error_code='cross_field', violation_error_message='A machine model cannot be an export edition of itself.'),
        ),
        migrations.AddField(
            model_name='modelexportmarket',
            name='machine_model',
            field=models.ForeignKey(help_text='The subject model this export-market row belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='export_markets', to='catalog.machinemodel'),
        ),
        migrations.AddField(
            model_name='modelexportmarket',
            name='target_market_location',
            field=models.ForeignKey(blank=True, help_text='The destination country, when known and seeded. Must be a top-level Location (a country).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_markets', to='catalog.location'),
        ),
        migrations.AddConstraint(
            model_name='modelexportmarket',
            constraint=models.CheckConstraint(condition=models.Q(('target_market_location__isnull', True), ('target_market_label', ''), _connector='OR'), name='catalog_modelexportmarket_target_at_most_one', violation_error_code='cross_field', violation_error_message='Set a target country or a market label — never both.'),
        ),
        migrations.AddConstraint(
            model_name='modelexportmarket',
            constraint=models.UniqueConstraint(condition=models.Q(('target_market_location__isnull', False)), fields=('machine_model', 'target_market_location'), name='catalog_modelexportmarket_unique_location_target'),
        ),
        migrations.AddConstraint(
            model_name='modelexportmarket',
            constraint=models.UniqueConstraint(condition=models.Q(('target_market_location__isnull', True)), fields=('machine_model',), name='catalog_modelexportmarket_unique_null_location'),
        ),
    ]
