# Generated by Django 6.0.6 on 2026-07-20 03:40

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_export_editions_and_markets'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemodel',
            name='manufacturer_model_identifier',
            field=models.CharField(blank=True, help_text="The manufacturer's own identifier for this model.", max_length=100, null=True, validators=[apps.core.validators.validate_no_mojibake], verbose_name='Manufacturer Model ID'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('manufacturer_model_identifier__isnull', True), models.Q(('manufacturer_model_identifier', ''), _negated=True), _connector='OR'), name='catalog_machinemodel_manufacturer_model_identifier_not_empty'),
        ),
    ]
