# Generated by Django 6.0.6 on 2026-07-26 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_promote_manufacturer_model_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateentity',
            name='year_end',
            field=models.PositiveSmallIntegerField(blank=True, help_text='DEAD FIELD — do not read or write. The asserted year the corporate entity ceased operations; see year_start for why it was retired. Use the derived year_of_last_model instead, with operating_status for whether the maker has actually stopped. Kept only so the cited claims behind it survive.', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='year_start',
            field=models.PositiveSmallIntegerField(blank=True, help_text='DEAD FIELD — do not read or write. The asserted corporate founding year, retired because it answers the wrong question: a company can incorporate years before its first machine and linger years after its last. Use the derived year_of_first_model instead, as the page and export APIs do. Kept only so the cited claims behind it survive.', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
