# Generated by Django 6.0.6 on 2026-07-26 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0027_alter_corporateentity_year_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="opdb_manufacturer_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="OPDB's manufacturer_id for this manufacturer.",
                null=True,
                unique=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
