# Generated by Django 6.0.6 on 2026-07-26 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0028_alter_manufacturer_opdb_manufacturer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corporateentity",
            name="year_end",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="DEAD FIELD — do not read or write. The asserted year the corporate entity ceased operations; see year_start for why it was retired. Use the derived year_of_last_model instead, with operating_status for whether the entity has actually stopped. Kept only so the cited claims behind it survive.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1800),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
    ]
