# Generated by Django 6.0.6 on 2026-08-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0029_alter_corporateentity_year_end"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cabinet",
            constraint=models.CheckConstraint(
                condition=models.Q(("slug", "unclassified"), _negated=True),
                name="catalog_cabinet_slug_not_unclassified",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameformat",
            constraint=models.CheckConstraint(
                condition=models.Q(("slug", "unclassified"), _negated=True),
                name="catalog_gameformat_slug_not_unclassified",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionstatus",
            constraint=models.CheckConstraint(
                condition=models.Q(("slug", "unclassified"), _negated=True),
                name="catalog_productionstatus_slug_not_unclassified",
            ),
        ),
    ]
