# Generated by Django 6.0.7 on 2026-08-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_reserve_unclassified_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='machinemodel',
            name='catalog_machinemodel_year_range',
        ),
        migrations.RemoveConstraint(
            model_name='machinemodel',
            name='catalog_machinemodel_month_range',
        ),
        migrations.RemoveConstraint(
            model_name='machinemodel',
            name='catalog_machinemodel_month_requires_year',
        ),
        migrations.RemoveIndex(
            model_name='machinemodel',
            name='catalog_mac_corpora_e8a031_idx',
        ),
        migrations.RemoveIndex(
            model_name='machinemodel',
            name='catalog_mac_technol_e73054_idx',
        ),
        migrations.RenameField(
            model_name='machinemodel',
            old_name='month',
            new_name='production_month',
        ),
        migrations.RenameField(
            model_name='machinemodel',
            old_name='year',
            new_name='production_year',
        ),
        migrations.AddIndex(
            model_name='machinemodel',
            index=models.Index(fields=['corporate_entity', 'production_year'], name='catalog_mac_corpora_4523c9_idx'),
        ),
        migrations.AddIndex(
            model_name='machinemodel',
            index=models.Index(fields=['technology_generation', 'production_year'], name='catalog_mac_technol_2a8e3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('production_year__isnull', True), models.Q(('production_year__gte', 1800), ('production_year__lte', 2100)), _connector='OR'), name='catalog_machinemodel_production_year_range'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('production_month__isnull', True), models.Q(('production_month__gte', 1), ('production_month__lte', 12)), _connector='OR'), name='catalog_machinemodel_production_month_range'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('production_month__isnull', True), ('production_year__isnull', False), _connector='OR'), name='catalog_machinemodel_production_month_requires_year', violation_error_code='cross_field', violation_error_message='production_month requires production_year.'),
        ),
    ]
