# Generated by Django 6.0.7 on 2026-08-19 06:51

import django.core.validators
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_rename_model_date_fields_to_production'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='machinemodel',
            name='catalog_mac_corpora_4523c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='machinemodel',
            name='catalog_mac_technol_2a8e3c_idx',
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='project_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='project_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='month',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(production_year__isnull=False, then=models.F('production_month')), default=models.F('project_month')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='year',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce('production_year', 'project_year'), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddIndex(
            model_name='machinemodel',
            index=models.Index(fields=['corporate_entity', 'year'], name='catalog_mac_corpora_e8a031_idx'),
        ),
        migrations.AddIndex(
            model_name='machinemodel',
            index=models.Index(fields=['technology_generation', 'year'], name='catalog_mac_technol_e73054_idx'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('project_year__isnull', True), models.Q(('project_year__gte', 1800), ('project_year__lte', 2100)), _connector='OR'), name='catalog_machinemodel_project_year_range'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('project_month__isnull', True), models.Q(('project_month__gte', 1), ('project_month__lte', 12)), _connector='OR'), name='catalog_machinemodel_project_month_range'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('project_month__isnull', True), ('project_year__isnull', False), _connector='OR'), name='catalog_machinemodel_project_month_requires_year', violation_error_code='cross_field', violation_error_message='project_month requires project_year.'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('project_year__isnull', True), ('production_year__isnull', True), ('project_year__lt', models.F('production_year')), models.Q(('project_year', models.F('production_year')), models.Q(('project_month__isnull', True), ('production_month__isnull', True), ('project_month__lte', models.F('production_month')), _connector='OR')), _connector='OR'), name='catalog_machinemodel_project_lte_production', violation_error_code='cross_field', violation_error_message='project date cannot be after production date.'),
        ),
    ]
