-- Generated by: python manage.py export_entity_registry
-- Do not edit manually — edit the models and re-run `make codegen`.
--
-- Why no view here spells an entity type the way Django stores it:
-- `LinkableModel.entity_type` is the canonical public name ('model',
-- 'person'), a content type row spells the same thing
-- 'catalog.machinemodel', and no string rule turns one into the other.
--
-- SQL rather than a data file because `entity_subjects` needs generated
-- table names, which no runtime read of JSON could supply.

CREATE OR REPLACE VIEW entity_registry AS
  SELECT * FROM (VALUES
    ('cabinet'                 , 'cabinets'                 , 'catalog.cabinet'                , 'catalog_cabinet'                , 'slug'),
    ('corporate-entity'        , 'corporate-entities'       , 'catalog.corporateentity'        , 'catalog_corporateentity'        , 'slug'),
    ('credit-role'             , 'credit-roles'             , 'catalog.creditrole'             , 'catalog_creditrole'             , 'slug'),
    ('display-subtype'         , 'display-subtypes'         , 'catalog.displaysubtype'         , 'catalog_displaysubtype'         , 'slug'),
    ('display-type'            , 'display-types'            , 'catalog.displaytype'            , 'catalog_displaytype'            , 'slug'),
    ('franchise'               , 'franchises'               , 'catalog.franchise'              , 'catalog_franchise'              , 'slug'),
    ('game-format'             , 'game-formats'             , 'catalog.gameformat'             , 'catalog_gameformat'             , 'slug'),
    ('gameplay-feature'        , 'gameplay-features'        , 'catalog.gameplayfeature'        , 'catalog_gameplayfeature'        , 'slug'),
    ('location'                , 'locations'                , 'catalog.location'               , 'catalog_location'               , 'location_path'),
    ('manufacturer'            , 'manufacturers'            , 'catalog.manufacturer'           , 'catalog_manufacturer'           , 'slug'),
    ('model'                   , 'models'                   , 'catalog.machinemodel'           , 'catalog_machinemodel'           , 'slug'),
    ('person'                  , 'people'                   , 'catalog.person'                 , 'catalog_person'                 , 'slug'),
    ('production-status'       , 'production-statuses'      , 'catalog.productionstatus'       , 'catalog_productionstatus'       , 'slug'),
    ('reward-type'             , 'reward-types'             , 'catalog.rewardtype'             , 'catalog_rewardtype'             , 'slug'),
    ('series'                  , 'series'                   , 'catalog.series'                 , 'catalog_series'                 , 'slug'),
    ('system'                  , 'systems'                  , 'catalog.system'                 , 'catalog_system'                 , 'slug'),
    ('tag'                     , 'tags'                     , 'catalog.tag'                    , 'catalog_tag'                    , 'slug'),
    ('technology-generation'   , 'technology-generations'   , 'catalog.technologygeneration'   , 'catalog_technologygeneration'   , 'slug'),
    ('technology-subgeneration', 'technology-subgenerations', 'catalog.technologysubgeneration', 'catalog_technologysubgeneration', 'slug'),
    ('theme'                   , 'themes'                   , 'catalog.theme'                  , 'catalog_theme'                  , 'slug'),
    ('title'                   , 'titles'                   , 'catalog.title'                  , 'catalog_title'                  , 'slug')
  ) AS t(entity_type, entity_type_plural, django_label, db_table, public_id_field);
COMMENT ON VIEW entity_registry IS
  'One row per catalog entity type — the entity_type this layer speaks and its plural, and the content-type label, table name and public id field the physical schema speaks. Join it to fc.django_content_type to decode a polymorphic reference; entity_type_of(table) spells a single one.';

-- entity_subjects — the polymorphic-reference resolver. `subject_public_id`
-- is NOT a slug: it is whatever the model declares as `public_id_field`,
-- `location_path` for Location, where live places share the slug `victoria`.
--
-- Restricted to `ClaimControlledModel`: a provenance entity (Actor,
-- ChangeSet, Source) is never a claim subject.
--
-- NOT LIVE-FILTERED: dropping a soft-deleted row would turn a retired subject
-- into an unresolvable one. Predicate on `subject_status`.
CREATE OR REPLACE VIEW entity_subjects AS
  SELECT
    subject_type,
    id        AS subject_id,
    public_id AS subject_public_id,
    name      AS subject_name,
    status    AS subject_status
  FROM (
              SELECT 'cabinet'                  AS subject_type, id, slug AS public_id, name, status FROM fc.catalog_cabinet
    UNION ALL SELECT 'corporate-entity'        , id, slug, name, status FROM fc.catalog_corporateentity
    UNION ALL SELECT 'credit-role'             , id, slug, name, status FROM fc.catalog_creditrole
    UNION ALL SELECT 'display-subtype'         , id, slug, name, status FROM fc.catalog_displaysubtype
    UNION ALL SELECT 'display-type'            , id, slug, name, status FROM fc.catalog_displaytype
    UNION ALL SELECT 'franchise'               , id, slug, name, status FROM fc.catalog_franchise
    UNION ALL SELECT 'game-format'             , id, slug, name, status FROM fc.catalog_gameformat
    UNION ALL SELECT 'gameplay-feature'        , id, slug, name, status FROM fc.catalog_gameplayfeature
    UNION ALL SELECT 'location'                , id, location_path, name, status FROM fc.catalog_location
    UNION ALL SELECT 'manufacturer'            , id, slug, name, status FROM fc.catalog_manufacturer
    UNION ALL SELECT 'model'                   , id, slug, name, status FROM fc.catalog_machinemodel
    UNION ALL SELECT 'person'                  , id, slug, name, status FROM fc.catalog_person
    UNION ALL SELECT 'production-status'       , id, slug, name, status FROM fc.catalog_productionstatus
    UNION ALL SELECT 'reward-type'             , id, slug, name, status FROM fc.catalog_rewardtype
    UNION ALL SELECT 'series'                  , id, slug, name, status FROM fc.catalog_series
    UNION ALL SELECT 'system'                  , id, slug, name, status FROM fc.catalog_system
    UNION ALL SELECT 'tag'                     , id, slug, name, status FROM fc.catalog_tag
    UNION ALL SELECT 'technology-generation'   , id, slug, name, status FROM fc.catalog_technologygeneration
    UNION ALL SELECT 'technology-subgeneration', id, slug, name, status FROM fc.catalog_technologysubgeneration
    UNION ALL SELECT 'theme'                   , id, slug, name, status FROM fc.catalog_theme
    UNION ALL SELECT 'title'                   , id, slug, name, status FROM fc.catalog_title
  );
COMMENT ON VIEW entity_subjects IS
  'One row per catalog entity of ANY type, keyed (subject_type, subject_id) the way a polymorphic reference names it — public id, name and status for resolving a claim, changeset or patch entry subject without branching on its type. NOT live-filtered; predicate on subject_status.';
