// Generated by: python manage.py export_catalog_meta
// Do not edit manually.

export const CATALOG_META = {
  cabinet: {
    entity_type: 'cabinet',
    entity_type_plural: 'cabinets',
    label: 'Cabinet',
    label_plural: 'Cabinets',
    relationships: {},
  },
  'corporate-entity': {
    entity_type: 'corporate-entity',
    entity_type_plural: 'corporate-entities',
    label: 'Corporate Entity',
    label_plural: 'Corporate Entities',
    relationships: {
      manufacturer: { target_type: 'manufacturer', many: false },
    },
  },
  'credit-role': {
    entity_type: 'credit-role',
    entity_type_plural: 'credit-roles',
    label: 'Credit Role',
    label_plural: 'Credit Roles',
    relationships: {
      machine_models: { target_type: 'model', many: true },
      series_credited: { target_type: 'series', many: true },
    },
  },
  'display-subtype': {
    entity_type: 'display-subtype',
    entity_type_plural: 'display-subtypes',
    label: 'Display Subtype',
    label_plural: 'Display Subtypes',
    relationships: {
      display_type: { target_type: 'display-type', many: false },
    },
  },
  'display-type': {
    entity_type: 'display-type',
    entity_type_plural: 'display-types',
    label: 'Display Type',
    label_plural: 'Display Types',
    relationships: {},
  },
  franchise: {
    entity_type: 'franchise',
    entity_type_plural: 'franchises',
    label: 'Franchise',
    label_plural: 'Franchises',
    relationships: {},
  },
  'game-format': {
    entity_type: 'game-format',
    entity_type_plural: 'game-formats',
    label: 'Game Format',
    label_plural: 'Game Formats',
    relationships: {},
  },
  'gameplay-feature': {
    entity_type: 'gameplay-feature',
    entity_type_plural: 'gameplay-features',
    label: 'Gameplay Feature',
    label_plural: 'Gameplay Features',
    relationships: {
      parents: { target_type: 'gameplay-feature', many: true },
    },
  },
  location: {
    entity_type: 'location',
    entity_type_plural: 'locations',
    label: 'Location',
    label_plural: 'Locations',
    relationships: {
      corporate_entities: { target_type: 'corporate-entity', many: true },
      parent: { target_type: 'location', many: false },
    },
  },
  manufacturer: {
    entity_type: 'manufacturer',
    entity_type_plural: 'manufacturers',
    label: 'Manufacturer',
    label_plural: 'Manufacturers',
    relationships: {},
  },
  model: {
    entity_type: 'model',
    entity_type_plural: 'models',
    label: 'Model',
    label_plural: 'Models',
    relationships: {
      cabinet: { target_type: 'cabinet', many: false },
      converted_from: { target_type: 'model', many: false },
      corporate_entity: { target_type: 'corporate-entity', many: false },
      display_subtype: { target_type: 'display-subtype', many: false },
      display_type: { target_type: 'display-type', many: false },
      game_format: { target_type: 'game-format', many: false },
      gameplay_features: { target_type: 'gameplay-feature', many: true },
      remake_of: { target_type: 'model', many: false },
      reward_types: { target_type: 'reward-type', many: true },
      system: { target_type: 'system', many: false },
      tags: { target_type: 'tag', many: true },
      technology_generation: { target_type: 'technology-generation', many: false },
      technology_subgeneration: { target_type: 'technology-subgeneration', many: false },
      themes: { target_type: 'theme', many: true },
      title: { target_type: 'title', many: false },
      variant_of: { target_type: 'model', many: false },
    },
  },
  person: {
    entity_type: 'person',
    entity_type_plural: 'people',
    label: 'Person',
    label_plural: 'People',
    relationships: {},
  },
  'reward-type': {
    entity_type: 'reward-type',
    entity_type_plural: 'reward-types',
    label: 'Reward Type',
    label_plural: 'Reward Types',
    relationships: {},
  },
  series: {
    entity_type: 'series',
    entity_type_plural: 'series',
    label: 'Series',
    label_plural: 'Series',
    relationships: {},
  },
  system: {
    entity_type: 'system',
    entity_type_plural: 'systems',
    label: 'System',
    label_plural: 'Systems',
    relationships: {
      manufacturer: { target_type: 'manufacturer', many: false },
      technology_subgeneration: { target_type: 'technology-subgeneration', many: false },
    },
  },
  tag: {
    entity_type: 'tag',
    entity_type_plural: 'tags',
    label: 'Tag',
    label_plural: 'Tags',
    relationships: {},
  },
  'technology-generation': {
    entity_type: 'technology-generation',
    entity_type_plural: 'technology-generations',
    label: 'Technology Generation',
    label_plural: 'Technology Generations',
    relationships: {},
  },
  'technology-subgeneration': {
    entity_type: 'technology-subgeneration',
    entity_type_plural: 'technology-subgenerations',
    label: 'Technology Subgeneration',
    label_plural: 'Technology Subgenerations',
    relationships: {
      technology_generation: { target_type: 'technology-generation', many: false },
    },
  },
  theme: {
    entity_type: 'theme',
    entity_type_plural: 'themes',
    label: 'Theme',
    label_plural: 'Themes',
    relationships: {
      parents: { target_type: 'theme', many: true },
    },
  },
  title: {
    entity_type: 'title',
    entity_type_plural: 'titles',
    label: 'Title',
    label_plural: 'Titles',
    relationships: {
      franchise: { target_type: 'franchise', many: false },
      series: { target_type: 'series', many: false },
    },
  },
} as const;

export type CatalogEntityKey = keyof typeof CATALOG_META;

export const MEDIA_CATEGORIES = {
  'gameplay-feature': ['other'],
  manufacturer: ['logo', 'other'],
  model: ['backglass', 'playfield', 'cabinet', 'other'],
  person: ['portrait', 'other'],
} as const;
