# Generated by Django 6.0.7 on 2026-09-07 00:33

import apps.accounts.models
import apps.accounts.usernames
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20, unique=True, validators=[apps.accounts.usernames.validate_username_format])),
                ('email', models.EmailField(max_length=254)),
                ('workos_user_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=10000)),
                ('actor', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='actors.actor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_unique_email_ci'), models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='accounts_user_email_not_blank'), models.CheckConstraint(condition=models.Q(('workos_user_id', ''), _negated=True), name='accounts_user_workos_user_id_not_blank'), models.CheckConstraint(condition=models.Q(('username__length__gte', 3)), name='accounts_user_username_min_length'), models.CheckConstraint(condition=models.Q(('username__length__lte', 20)), name='accounts_user_username_max_length')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
