# Generated by Django 6.0.3 on 2026-06-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entitymedia',
            name='media_entitymedia_one_primary_per_category',
        ),
        migrations.RemoveConstraint(
            model_name='entitymedia',
            name='media_entitymedia_one_primary_uncategorized',
        ),
    ]
