# Generated by Django 6.0.3 on 2026-06-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_entitymedia_media_entitymedia_one_primary_per_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitymedia',
            options={'ordering': ['content_type', 'object_id', '-is_primary', 'asset_id']},
        ),
        migrations.RemoveField(
            model_name='entitymedia',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entitymedia',
            name='updated_at',
        ),
    ]
