# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="priority",
            field=models.PositiveSmallIntegerField(
                help_text=(
                    "Trust weight feeding claim resolution; higher wins. "
                    "Mirrored from the backing record."
                ),
            ),
        ),
    ]
